### ISSUE TITLE
Add small, medium, large as option for link attribute

### ISSUE THREAD

**Issue by DenisLanz** [jancbeck/kirby-responsive-images#4]
It would be nice to be able to link to the thumb created by the plugin in the link attribute similar to `self` like `small`, `medium`, `large` or just `large`. 

Like this:

```
(image: file.jpg link: large)
```

**Comment by jancbeck** [comment]
Interesting idea, but when would you ever link to a file that is not the original or largest possible size?

**Comment by DenisLanz** [comment]
Think of editor who don't care about mobile user or don't know how to resize images and just upload a super large image that necessarily doesn't have to be that big.

**Comment by jancbeck** [comment]
Ok I get that, but as a visitor of the site wouldn't I want to have access to the image in the best possible quality? If an editor doesn't care about mobile users, why would they bother learning about the size keywords?

**Comment by jancbeck** [comment]
Thanks @Designscheu I just added this feature in 43e9c536e996c592fa600adfb4f973d31d625cf1
